---
name: Archive snapshot

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  bundle:
    name: Archive Snapshot
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r ./archiver/requirements.txt
      - run: python ./archiver/main.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Archive snapshot
